# Generated by Django 3.1 on 2020-09-09 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=datetime.datetime(2020, 9, 9, 9, 31, 21, 173386, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
