# Generated by Django 3.1 on 2020-09-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.DeleteModel(
            name='productImage',
        ),
    ]
