# Generated by Django 3.1 on 2020-09-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=6)),
                ('status', models.CharField(max_length=80)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=10)),
                ('date_of_payment', models.DateTimeField()),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('date_placed', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField()),
                ('order_price', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.cart')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('shipping_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingprovider')),
            ],
        ),
    ]
